### ISSUE TITLE
Metrics are not sent to Cloudwatch when the tests are executed in Docker container

### ISSUE THREAD

**Issue by AnatoliiHanziuk** [loadimpact/k6#1812] opened 2021-01-19 17:44 UTC
I'm trying to execute tests in the Docker container and send the metrics to the EC2 instance where CloudWatchAgent is installed and configured. However, I don't see the metrics in the Cloudwatch and cannot understand whether they were sent by k6 or not to the EC2 instance with CloudWatchAgent.
I'm not sure that k6 supports sending metrics of the tests that are executed in the Docker container because [here](https://k6.io/docs/results-visualization/amazon-cloudwatch) I didn't clear confirmation of such possibility.

## Environment

- k6 version: 0.29.0
- Docker version and image, if applicable: 20.10.2

## Expected Behavior
Execution metrics should appear in Cloudwatch in `k6` namespace.

## Actual Behavior
`k6` namespace is not created and there are no relevant metrics in CloudWatch.

## Steps to Reproduce the Problem
1. Create Docker image with tests:
```
FROM loadimpact/k6:0.29.0
ENV TEST_FILE=None
ENV K6_STATSD_ADDR=localhost:8125
WORKDIR .
COPY k6/ .
ENTRYPOINT ["sh", "-c"]
CMD ["k6 run $TEST_FILE"]
```
2. Create AWS CodeBuild step as a part of AWS CodePipeline to execute k6 tests.
3. Create EC2 instance based on Amazon Linux 2.
4. Create IAM role with policy `CloudWatchAgentServerPolicy`
5. Attach created IAM role to EC2 instance
6. Configure EC2 instance using [instructions](https://k6.io/docs/results-visualization/amazon-cloudwatch). Install cloudwatch agent using `sudo yum install amazon-cloudwatch-agent`
7. Copy private IP address of EC2 instance
8. As a part of CodeBuild stage execute tests in Docker container using command
```
docker run -e TEST_FILE=myTests.js -e K6_STATSD_ADDR=<ip_address_of_ec2_with_cwagent> k6Tests
```
9. After the execution is complete check Cloudwatch metrics for the same region where EC2 instance is located.

**Comment by na--** [comment] 2021-01-19 18:09
Setting `K6_STATSD_ADDR=<ip_address_of_ec2_with_cwagent>` is not enough to make k6 start emitting metrics to statsd, you need to explicitly use the CLI flag as well, like this: `k6 run --out statsd`, so please try adding that to the `CMD` directive in your `Dockerfile`. If that is still not enough, please also run k6 with the `--verbose` flag and post the sanitized logs.

**Comment by AnatoliiHanziuk** [comment] 2021-01-20 07:54
I added `--out statsd` and `--verbose` flags.

Please find the logs you requested:
```
time="2021-01-19T21:09:13Z" level=debug msg="Starting emission of VU metrics..." component=engine
--
216 | time="2021-01-19T21:09:13Z" level=debug msg="statsd: Running!" type=statsd
217 | time="2021-01-19T21:09:13Z" level=debug msg="Metrics processing started..." component=engine
218 |  
219 | Run            [ 100% ] setup()
220 | ramping_load   [   0% ]
221 | time="2021-01-19T21:09:14Z" level=debug msg="Start all executors..." phase=local-execution-scheduler-run
222 | time="2021-01-19T21:09:14Z" level=debug msg="Starting executor" executor=ramping_load startTime=0s type=ramping-vus
223 | time="2021-01-19T21:09:14Z" level=debug msg="Starting executor run..." duration=2m0s executor=ramping-vus maxVUs=120 numStages=1 scenario=ramping_load startVUs=0 type=ramping-vus
224 | time="2021-01-19T21:09:14Z" level=debug msg="Pushing metrics to server" samples=15 type=statsd
225 |  
226 | running (0m01.0s), 000/120 VUs, 0 complete and 0 interrupted iterations
227 | ramping_load   [   0% ] 000/120 VUs  0m00.3s/2m00.0s
228 | time="2021-01-19T21:09:15Z" level=debug msg=Start executor=ramping-vus scenario=ramping_load vuNum=0
229 | time="2021-01-19T21:09:15Z" level=debug msg="Pushing metrics to server" samples=2 type=statsd
230 |  
231 | running (0m02.0s), 001/120 VUs, 0 complete and 0 interrupted iterations
232 | ramping_load   [   1% ] 001/120 VUs  0m01.3s/2m00.0s
233 | time="2021-01-19T21:09:15Z" level=debug msg="running thresholds" component=engine m="failed authentication request"
234 | time="2021-01-19T21:09:15Z" level=debug msg="running thresholds" component=engine m=http_req_duration
235 | time="2021-01-19T21:09:16Z" level=debug msg=Start executor=ramping-vus scenario=ramping_load vuNum=1
236 | time="2021-01-19T21:09:16Z" level=debug msg="Pushing metrics to server" samples=12 type=statsd
```
The rest of the logs have the same pattern.
However, in Cloudwatch k6 log groups is absent.

**Comment by na--** [comment] 2021-01-20 08:12
I am not very familiar with statsd or cloudwatch, but I assume the issue is on their side, k6 seems to have sent the metrics successfully. Otherwise, there would be a `Couldn't commit a batch` error in the logs, after `Pushing metrics to server`, see https://github.com/loadimpact/k6/blob/45fff81b0b3af8d174c960450d16f5c4431ef9a4/stats/statsd/common/collector.go#L148-L156

**Comment by AnatoliiHanziuk** [comment] 2021-01-20 08:48
I feel that the CodeBuild just doesn't have needed access to the EC2 instance where the CloudWatch agent is started.  
If I understand correctly, k6 uses async push model and doesn't check that the metrics successfully arrived to the destination. 

BTW, you're saying that the problem could be on statsd or cloudwatch side - does it mean that k6 doesn't have any integration and system tests that verify interaction at least with statsd? If yes then meybe it could be a good idea to add tests for the integration k6 has?

**Comment by na--** [comment] 2021-01-20 09:11
k6 [pushes metrics](https://github.com/loadimpact/k6/blob/45fff81b0b3af8d174c960450d16f5c4431ef9a4/stats/statsd/common/collector.go#L96-L111) to statsd every `K6_STATSD_PUSH_INTERVAL` (1s by default) and at the end of the test run. All I said in my previous message was that, in your case, based on the logs you provided, at least 3 of these pushes appears to have been successful. 

What statsd does with these metrics after that is out of our hands. There are literally countless possible scenarios, including at least 3 statsd-based commercial services that I can think of, and we can't realistically test them all. How and why would k6 check if the metrics arrived "to the destination", how would it even know what the destination was? k6 is a load testing tool, verifying that some metrics were properly processed by a complicated proprietary data pipeline is quite a bit out of scope for it...

The [current statsd/datadog tests](https://github.com/loadimpact/k6/blob/master/stats/statsd/common/testutil/test_helper.go) in k6 spin up a UDP server and listen for metrics, comparing byte-for-byte that k6 sends the correct statsd line format. This seems like the limit of what is sane to test in k6 - we thoroughly ensure we've actually sent the correct data to statsd... Anything beyond that point should solely be the concern of statsd (or whatever commercial service implements the same protocol). 

In your case, I suggest you look at the statsd and any other logs you have, to figure out what happens with the data after k6 has sent it. I'm closing this issue, since this doesn't seem like a bug in k6 and help with CodeBuild/EC2/CloudWatch/etc. is a bit out of scope for the k6 issues as well. You can try the community forum (https://community.k6.io), though some place that deals with AWS or StackOverflow might be a better fit for this question.

**Closed by na--** 2021-01-20 09:11 UTC
Labels: bug
