### ISSUE TITLE
Sending null values in post request

### ISSUE THREAD

**Issue by Lex-talionis** [loadimpact/k6#1184] opened 2019-10-04 11:28 UTC
Hi, when trying to sending a null value to a post endpoint, k6 converts null into `'<nil>'`. is there a way to fix this in my end?

**Comment by na--** [comment] 2019-10-04 11:54
Can you post your code and tell us which k6 version you are using, since this seems like a bug, but I can't reproduce it. This code:
```js
import http from "k6/http";

export default function () {
    let resp = http.post("https://httpbin.org/post", null);
    console.log(resp.body);
}
```

produces 
```
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Content-Length": "0", 
    "Host": "httpbin.org", 
    "User-Agent": "k6/0.25.1 (https://k6.io/)"
  }, 
  "json": null, 
  "url": "https://httpbin.org/post"
} 
```
which seems normal

**Comment by Lex-talionis** [comment] 2019-10-04 13:16
Hi @na-- thanks for your quick response. Im sorry my last post wasnt clear at all

 ```
            let url = httpParams.url + "/api/v1/login";
            let payload = {
                username: "myusername",
                password: "mypassword",
                company_id: null ,
                vendor_id : null ,
                ldap_id : null ,
            };
            let params = {
                "Content-Type": "application/json"
            };
            let res = http.post(url, payload, params);
```

my response i get within the node api is 

```
{
  company_id: '<nil>',
  ldap_id: '<nil>',
  password: 'mypassword',
  username: 'mypassword',
  vendor_id: '<nil>' 
}
```

**Comment by MStoykov** [comment] 2019-10-04 14:13
This is duplicate of #878, so I am closing this. 

For a quick fix you can use`JSON.stringify(payload)`(the issue above explains what is happening but  as : 
```js
import http from "k6/http";

export default function () {
    let payload = {
        username: "myusername",
        password: "mypassword",
        company_id: null ,
        vendor_id : null ,
        ldap_id : null ,
    };
    let params = {
        "Content-Type": "application/json"
    };
    let resp = http.post("https://httpbin.org/post", JSON.stringify(payload), params);
    console.log(resp.body);
}
```
will get you: 
```json
 {
  "args": {},
  "data": "{\"username\":\"myusername\",\"password\":\"mypassword\",\"company_id\":null,\"vendor_id\":null,\"ldap_id\":null}",
  "files": {},
  "form": {},
  "headers": {
    "Content-Length": "99",
    "Host": "httpbin.org",
    "User-Agent": "k6/0.26.0-dev (https://k6.io/)"
  },
  "json": {
    "company_id": null,
    "ldap_id": null,
    "password": "mypassword",
    "username": "myusername",
    "vendor_id": null
  },
  "origin": "46.233.49.37, 46.233.49.37",
  "url": "https://httpbin.org/post"
}
```
I have also opened new issue to fix the problem when urlencoding

**Closed by MStoykov** 2019-10-04 14:13 UTC
Labels: bug, high prio

**Comment by Lex-talionis** [comment] 2019-10-04 14:17
@MStoykov thanks for your response i did have a check on existing issues and couldn't find a similar one, obviously i didn't look hard enough.

**Comment by na--** [comment] 2019-10-07 06:41
Don't worry @Lex-talionis, the issue wasn't easy to find since it stated the same problem in a different way... We just knew it because we've hit it before, and because we're currently investigating how to add a new and better HTTP API in k6 that would both be more flexible, and also solve issues like this that such confusion and frustration.

**Comment by aniketRaj-goPlus** [comment] 2023-03-14 11:02
Use blank string instead of null in your json format like this: 

`import http from "k6/http";

export default function () {
    let payload = {
        username: "myusername",
        password: "mypassword",
        company_id: "" ,
        vendor_id : "" ,
        ldap_id : "" ,
    };}`
