### ISSUE TITLE
Provide docker-compose setup for k6 + InfluxDB + Grafana

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#176] opened 2017-04-10 07:54 UTC
We want a docker-compose setup that starts an InfluxDB container, a Grafana container, and allows the user to run k6 with e.g. `docker-compose run k6 ...` using this storage backend.

The idea is to get a simple-to-setup, self-contained k6 environment where results are stored in a db and the user can create and view graphs from their test runs.

**Comment by liclac** [comment] 2017-04-10 14:41
👍 

The problem is, I don't think `docker compose` can take arguments… or can it?

**Comment by ragnarlonn** [comment] 2017-04-11 07:48
I think it does - check out https://docs.docker.com/compose/reference/run/

If I understand things correctly, you can set up your multi-instance environment with "docker-compose up" and then use "docker-compose run [service] [args]" to execute one-off commands inside a container. It looks to me like that would make our use-case doable, but I could have misunderstood something I guess.

**Comment by liclac** [comment] 2017-04-11 11:42
Oh, that's an interesting way to do it, actually. A k6 container with no arguments would terminate with the default help message right away, so we could have it start that way, then use `docker-compose run k6 …`. I was thinking of passing the arguments straight to docker-compose, so you'd run a full environment per-test.

**Comment by ragnarlonn** [comment] 2017-04-19 09:38
Comments to bountyhunters: 

- check out https://github.com/loadimpact/k6/blob/master/Dockerfile.grafana for inspiration

- the docker-compose setup should create three containers: one with InfluxDB, one with Grafana and one with k6

- suggested mode of operation is to do `docker-compose up` to start an InfluxDB container and a Grafana container and then `docker-compose run k6` to execute k6, which should then send results to the InfluxDB instance. Here, we might want to add support in k6 for specifying a default --out parameter through environment variables. Then this solution could set that environment variable to make k6 output results to the InfluxDB instance by default when the user runs `docker-compose run k6`

**Comment by gbts** [comment] 2017-04-24 06:30
Can you also close this issue now that #183 has been merged?

**Closed** 2017-04-24 14:02 UTC
