### ISSUE TITLE
Don't reuse connections between VU iterations

### ISSUE THREAD

**Issue by liclac** [loadimpact/k6#54] opened 2016-12-22 17:17 UTC
All these zeroes in `http_req_connecting`…

**Comment by robingustafsson** [comment] 2017-04-13 12:08
@ragnarlonn Could you not create the same behavior by having a while-true loop?

The default should IMO be to reset connections.

**Comment by ragnarlonn** [comment] 2017-04-16 10:19
ok, I agree that keeping connections alive over iterations is an edge case so doing it in a while-true loop is fine.

  /Ragnar

**Comment by micsjo** [comment] 2017-04-19 16:22
FYI I have a use case where a load balancer (BigIP F5 as usual...) maintains sessions by SSL connection ID. Not a good choice since you cannot control how connections are reused by the client, especially across proxies but it is what it is. It would be good to be able to control how connections are reused across iterations.

**Comment by liclac** [comment] 2017-04-19 20:05
A `while(true)` loop will never report any metrics, because the last iteration of a script is always discarded, but again - what is the use case here?

**Comment by micsjo** [comment] 2017-05-02 22:08
@liclac What does "shared transport" mean? Does it imply VUs will share tcp connections?

**Comment by ragnarlonn** [comment] 2017-05-03 11:19
@liclac I still get problems running e.g. 50 VUs and a script that iterates very quickly. I found that it can be fixed by increasing MaxIdleConnsPerHost for the TCP transport, according to the answer to this SO question: http://stackoverflow.com/questions/39813587/go-client-program-generates-a-lot-a-sockets-in-time-wait-state

**Comment by ragnarlonn** [comment] 2017-05-03 11:27
When I add those params I can use a couple of hundred VUs before I run into another issue: DNS lookups start to fail.ERRO[0003] GoError: Get http://test.loadimpact.com: dial tcp: lookup test.loadimpact.com: no such host
	at native
") That behaviour is related to a lack of file descriptors (ulimit -n). Increasing the number of allowed open files fixes it and I can use a lot more VUs.

I think these things are problems people will encounter quite often, so maybe it'd be an idea to catch the errors and display some suggestion about what the root cause could be?  I.e. instead of just saying "dial tcp [ip-address]: connect: can't assign requested address" we might add some extra tex

**Comment by liclac** [comment] 2017-05-03 12:15
I *want* to just cache DNS lookups and exclude that from metrics, because it's not a very useful metric - the results depend entirely on infrastructure wholly unrelated from the system you're actually trying to test. See #41.

What I just did was explicitly disable HTTP keepalives; the shared transport is mostly preparation for some kind of optimization here, but I'm honestly not well enough versed in the semantics of this to tell if there's a real difference between an idle connection and keep-alive…

**Comment by ragnarlonn** [comment] 2017-05-03 12:54
I'd say: yes, cache DNS lookups and remove the DNS lookup time metric for now. We can reintroduce it later, if people seem to want it. It is better to remove this potential road block for novice users than keep a metric noone is likely to use.

And keeping a socket pool per VU and reusing those sockets between iterations by default sounds like a good idea to me.

**Comment by liclac** [comment] 2017-05-03 19:39
VUs now have their own connection pools, needs a commandline switch to disable.

**Closed** 2017-05-09 13:56 UTC
Labels: bug

**Comment by jcody28** [comment] 2022-08-10 19:58
Thanks so much - adding the following in options helped me greatly:
    noConnectionReuse: true
my connections close the socket with a FIN/ACK appropriately after each vu iteration, and new connections are seen with a proper SYN sequence for each subsequent vu iteration.
