### ISSUE TITLE
k6 --insecure-skip-tls-verify is not working as expected

### ISSUE THREAD

**Issue by uvaisibrahim** [loadimpact/k6#1455] opened 2020-05-19 08:10 UTC
I have tried both k6 binary and docker image, and in both the --insecure-skip-tls-verify flag is not working to write data to an influxdb endpoint which is an https endpoint. I tried like this.

`docker run -v /root/script.js:/script.js -i loadimpact/k6 run --insecure-skip-tls-verify -vu 5 --duration 5s --out influxdb=https://my.test-influxdb.com/mydb /script.js`

But it gave error as given below.

`
time="2020-05-19T07:50:21Z" level=debug msg="InfluxDB: Writing..." points=1291
time="2020-05-19T07:50:21Z" level=error msg="InfluxDB: Couldn't write stats" error="Post https://my.test-influxdb.com/write?consistency=&db=uvi&precision=ns&rp=: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"UVI CORP Enterprise Issuing CA 01\")"
`

**Comment by imiric** [comment] 2020-05-19 14:52
Hi, thanks for reporting this.

The `--insecure-skip-tls-verify` option only works for HTTPS requests from inside the script. This is not documented thoroughly, so I understand the confusion.

I confirmed the same behavior with the InfluxDB output, and one workaround I used was to add the root CA to my system's certs (`/etc/ssl/certs` on Linux), but this is obviously a hassle you'd like to avoid.
I'd consider this a bug and `--insecure-skip-tls-verify` should apply for all HTTPS requests, including outputs. It's unlikely this will be fixed in the short-term since the team is focused on a major upcoming release, but we'll plan it soon after that. cc: @na-- @MStoykov

**Comment by na--** [comment] 2020-05-19 14:58
The InfluxDB has [its own option](https://github.com/loadimpact/k6/blob/9586f2f4624548e40e9a0567cf821b5523489a36/stats/influxdb/config.go#L41) to allow insecure connections, `K6_INFLUXDB_INSECURE`. This doesn't seem to be documented though :disappointed:

**Comment by MStoykov** [comment] 2020-10-01 07:58
The influxdb option is now documented I am leaving this open as `--insecure-skip-tls-verify` still should be docuemented to only work on vu code requests

**Closed** 2020-10-23 09:56 UTC
Labels: docs
