### ISSUE TITLE
`docker-compose up grafana`: Service 'grafana' failed to build

### ISSUE THREAD

**Issue by sgargel** [loadimpact/k6#282] opened 2017-07-13 09:56 UTC
Running `docker-compose up grafana` returns:
<pre>
ERROR: Service 'grafana' failed to build: 
The command '/bin/sh -c bash -c '/run.sh & sleep 15 && curl -s -H "Content-Type: application/json" -X POST     --data '"'"'{"name": "myinfluxdb", "type": "influxdb", "access": "proxy", "url": "http://influxdb:8086", "database": "k6", "isDefault": true}'"'"'     http://admin:admin@localhost:3000/api/datasources     && kill -SIGINT %%'' returned a non-zero code: 7
</pre>

**Comment by MWeesenaar** [comment] 2017-07-13 11:42
Hi @sgargel ,

Could you provide me somewhat more information?
What docker version are you running, what previous steps did you execute, which version of k6 are you using...?

I will, in the meanwhile, have a look myself.

**Comment by MWeesenaar** [comment] 2017-07-13 13:13
According to `man curl`, error 7 is: `Failed to connect to host.`
I guess that you don't have InfluxDB running.

I made a documentation change suggestion so it is more clear and easier to use.

For now, please use `docker-compose up -d influxdb grafana` instead of only `docker-compose up grafana`.

**Comment by MWeesenaar** [comment] 2017-07-18 11:08
I think this issue can be closed in two days, if @sgargel does not come back with feedback.

**Comment by MWeesenaar** [comment] 2017-07-23 07:40
Please close ticket, since there has been no reply.

**Closed** 2017-07-24 08:29 UTC

**Comment by ortizman** [comment] 2017-08-02 01:17
Hi, I have this same error. 
I follow the steps of the documentation

$  sudo docker-compose up -d influxdb grafana
 returns:

ERROR: Service 'grafana' failed to build: The command '/bin/sh -c bash -c '/run.sh & sleep 15 && curl -s -H "Content-Type: application/json" -X POST     --data '"'"'{"name": "myinfluxdb", "type": "influxdb", "access": "proxy", "url": "http://influxdb:8086", "database": "k6", "isDefault": true}'"'"'     http://admin:admin@localhost:3000/api/datasources     && kill -SIGINT %%'' returned a non-zero code: 7


Docker version 17.06.0-ce, build 02c1d87
docker-compose version 1.14.0, build c7bdf9e

**Comment by jfstgermain** [comment] 2017-12-18 19:37
Hello, I get the same error as well @MWeesenaar 

Docker version 17.09.0-ce, build afdb6d4
docker-compose version 1.17.0, build ac53b73

**Comment by MWeesenaar** [comment] 2017-12-18 20:38
On what git reversion are you testing?
You can get it by executing the following: `git rev-parse --verify HEAD`

**Comment by jfstgermain** [comment] 2017-12-18 20:49
The sleep value in the grafana dockerfile seems to be the problem.  I increased the value to 30 and that error is now gone... Thanks for your quick response

**Comment by MWeesenaar** [comment] 2017-12-18 20:50
Could you drop the specs of your machine (OS, CPU, memory, disk)? I might be able to reproduce it with a local VirtualMachine.

**Comment by jfstgermain** [comment] 2017-12-18 20:53
I'm running ubuntu in virtualbox, that's def the issue, things are a bit slooow.
Win10 host, ubuntu 17.10 guest, virtualbox 5.2.2, 8gb ram, intel i7 @ 3.4ghz...
