### ISSUE TITLE
GoAway error on files POST requests

### ISSUE THREAD

**Issue by marlukjanska** [loadimpact/k6#1091] opened 2019-07-29 13:59 UTC
I was doing a single file upload for number of users initiated via VUs and for some users I was getting the GO AWAY error.
![image](https://user-images.githubusercontent.com/34064916/62054405-69291900-b211-11e9-8eaf-f943cfe5017c.png)

After a bit of investigation I've found the following article: https://www.endgame.com/blog/technical-blog/investigating-http2-performance-go

I was wondering if the issue is related to not only our server configuration, but also to the GO http client in k6?

**Comment by MStoykov** [comment] 2019-07-29 15:50
If you are using nginx as a server, than, as the article you linked says, it has a maximum amount of requests it will handle before deciding to close the connection. IMO opinion this should be raised to well into a million, or possibly even disabled if they have added the option after 2-3 years since I last tried to disable it. 

But k6 does actually uses `GetBody` in order for in those cases(and others) to not actually get this error. I did just test it with nginx and I even lowered the maximum and checked that we do actually make a new connection. Everything appears to work with at least v0.24.0 and my current development build (which is the current master + unrelated patches).

 Can you provide us with a minimal script that provokes this? Maybe in some cases we do not use `GetBody`? Also if you can tell us with what version of k6 you are running? Possibly version of nginx if this turns out to be relevant, but ... I hardly doubt it.

**Comment by marlukjanska** [comment] 2019-07-30 09:28
@MStoykov I noticed that you've added a label 'bug'. Do you still need details like k6 version and the script excerpt? 
Thanks!

**Comment by MStoykov** [comment] 2019-07-30 10:58
Hi, Sorry, in my original post I said that I did test and couldn't find the bug and was sure we were using GetBody ... as I was pretty sure we have a test to catch another case where it is needed (Posts with redirects, or any request with a body :)) 
But after nearly two hours of going through code history this is apparently totally not true. I have no idea why I though so ... maybe I though of it at some point and never wrote it down? Either way I am very sorry. At this point 
1. I have reproduced the issue (I needed to have batches of requests or multiple VUs)
2. I have a patch that fixes it. Hopefully it will get merged ... but I don't know if we are going to put it in 0.25.0 as we are at the later stages of testing it . Maybe 0.25.1 we will see.

as the article suggests you can (for now) up nginx's max requests per http2 connection :)

**Comment by marlukjanska** [comment] 2019-07-30 11:00
Thanks for this @MStoykov! :)

**Comment by MStoykov** [comment] 2019-07-30 11:04
Thank you, for reporting it :)

**Closed** 2019-08-05 06:38 UTC
Labels: bug
