### ISSUE TITLE
Can't find the traget JS file when running K6 using docker in Jenkins

### ISSUE THREAD

**Issue by hassanbakerrts** [loadimpact/k6#1200] opened 2019-10-10 18:07 UTC
I have a Jenkins job that runs a JS code. Here is an excerpt of Groovy script:

```            sh 'docker run -v "$(pwd)/src":/src  -i loadimpact/k6 run -e BASE_URL="http://feature-env.com" -e  MOBILE_URL="https://feature-env.com" -e VUs=${VUs} --vus ${VUs} --iterations ${iterations}  /src/script.js'```

Now this runs fine locally but when I run it in Jenkins it gives me the following: 

```
level=error msg="The moduleSpecifier \"file:///src/script.js\" couldn't be found on local disk. Make sure that you've specified the right path to the file. If you're running k6 using the Docker image make sure you have mounted the local directory (-v /local/path/:/inside/docker/path) containing your script and modules so that they're accessible by k6 from inside of the container, see https://docs.k6.io/v1.0/docs/modules#section-using-local-modules-with-docker.
```

I'm sure that I'm in the right directory since the docker command above is translated as:

```docker run -v /var/jenkins_home/workspace/Mobile_load-test/load-tests/src:/src -i loadimpact/k6 run -e BASE_URL=http://feature-env..com -e MOBILE_URL=https://feature-env..com -e VUs=100 --vus 100 --iterations 100 /src/script.js```

And my script is under `/load-tests/src`. I also tried to change the working directory using `-w /src` and calling the script name without any slashes but K6 was trying to fetch the file as http request as `http://script.js`

Note: This might be related to https://github.com/loadimpact/k6/issues/1126

**Comment by na--** [comment] 2019-10-10 18:16
I'm a bit surprised that `$(pwd)` would work in that command, but if it's resolved correctly, then I have no idea what the issue could be. Just in case, can you just try to `cat` the ` /src/script.js` file instead of running k6 with it? Or `ls /src`? So, something like this:
```
sh 'docker run -v "$(pwd)/src":/src --entrypoint cat -i loadimpact/k6 /src/script.js'
```

Also, if that works correctly, can you show the result of running k6 with the `--verbose` flag?

**Comment by hassanbakerrts** [comment] 2019-10-10 18:23
This is what I got:
`cat: can't open '/src/script.js': No such file or directory`

**Comment by na--** [comment] 2019-10-10 18:57
Well, then this isn't a k6 problem - for some reason your script just isn't properly mounted in that folder. Try to debug what's happening in your container, for example by overwriting the entrypoint with `mount` or `ls` and checking what `/src` actually contains.

**Comment by hassanbakerrts** [comment] 2019-10-10 20:43
@na-- just to clarify, that output from Jenkins. In my local machine it shows the content of the `script.js`

**Comment by na--** [comment] 2019-10-10 21:00
Well OK, but if `cat` can't find the file on the Jenkins machine, then k6 also won't be able to :wink: My suspicion is that `$(pwd)` doesn't behave how you expect in that command, but you'd have to debug this particular Jenkins issue yourself, I can't help you with that.

**Comment by na--** [comment] 2019-10-11 06:41
I'm closing this, since it doesn't seem to be a k6 bug, but feel free to reopen if that's not the case. Also, if you find what the underlying Jenkins/docker issue is, please post it here, so other people that hit a similar issue in the future may find it.

**Closed by na--** 2019-10-11 06:41 UTC

**Comment by MattGson** [comment] 2021-11-09 03:06
Any update on this? Using without $PWD is a pain in the ass.

**Comment by MStoykov** [comment] 2021-11-09 09:32
@MattGson this is not a problem with `k6` but with some usage of docker.
 
As was mentioned above if `cat` can't find the file, k6 isn't going to be able to do it either. Whether this is a problem with `jenkins`, `docker` or the (CI/bash) script that is used is a different question, that again is unrelated to k6. 

If you have a different reproduction that does look like k6 is doing something else, please open another issue, but this one quite clearly IMO is not a problem with k6.
