### ISSUE TITLE
Support for custom CA Cert

### ISSUE THREAD

**Issue by tommysitu** [loadimpact/k6#218] opened 2017-05-12 10:05 UTC
I need to load test our SaaS platforms which run HTTPS servers that require CA certs.

In `curl`, I can do this to send request: `curl https://my-test-server.com --cacert ca.pem`. 
 
I've tried out different tools like `vegeta`, `ab`, `hey`, `wrk2`, but none of them can handle the SSL handshake probably. 

If K6 can support custom CA cert for HTTPS requests, that would be wonderful.

**Comment by robingustafsson** [comment] 2017-05-12 10:12
Found this sample how to use custom CA certs in Go which could come in handy when this is picked up: https://gist.github.com/michaljemala/d6f4e01c4834bf47a9c4

**Comment by gunisp01** [comment] 2017-05-12 13:51
This is something which is high priority requirement for us too at BBC and waiting for SSL support desperately.

**Comment by aidylewis** [comment] 2017-05-12 14:10
[Vegeta](https://github.com/tsenart/vegeta) supports SSL client certs:

**Comment by tommysitu** [comment] 2017-05-12 14:46
I've tested vegeta, they don't seem to support CA cert, here is the issue I opened: https://github.com/tsenart/vegeta/issues/231

**Comment by aidylewis** [comment] 2017-05-12 15:09
Are you missing a key flag?

**Comment by bagder** [comment] 2017-05-12 15:10
It is important to not confuse CA cert with client cert. The CA cert bundle is used to verify the server. A client cert is used to pass to the server from the client to authenticate to connection.

**Comment by tommysitu** [comment] 2017-05-12 15:16
There is a good illustration in this link: 
https://www.ibm.com/support/knowledgecenter/SSRMWJ_7.0.1/com.ibm.isim.doc/securing/cpt/cpt_ic_security_ssl_scenario.htm

I am doing one-way SSL, therefore I don't have the key. Only a CA cert is required to authenticated with the server, which is what `--cacert` flag does in `curl`.

**Comment by micsjo** [comment] 2017-05-12 15:58
Do you really need the server certificate validated while running performance tests? Wouldn't it be simpler to just ignore (skip)?

**Comment by tommysitu** [comment] 2017-05-12 16:19
I am interested in the overall performance of our platform, including the potential overhead introduced by the SSL authentication.

**Comment by micsjo** [comment] 2017-05-12 16:42
I am confused. The SSL connection will be established but k6 will skip the certificate validation. AFAIK the client side certificate validation has no server side impact. Or am I missing something here?

**Comment by liclac** [comment] 2017-05-12 16:43
I think we're getting this and #206 all muddled up right now; is this a duplicate of that or asking to be able to add a CA certificate to the trust store (without adding it to the system pool)?

**Comment by micsjo** [comment] 2017-05-12 16:45
Because my next question is if k6 will look in the system pool? Then it can just be added there.

**Comment by liclac** [comment] 2017-05-12 16:45
Yes, k6 defaults to using the system's pool of trusted certificates. I can see a use case for wanting a certificate trusted only for a certain test run, however.

**Comment by tommysitu** [comment] 2017-05-12 16:49
Ok, if there is an option like the `--insecure` flag in `curl` that will be fine.

**Comment by liclac** [comment] 2017-05-12 16:50
It exists! `k6 run --insecure-skip-tls-verify ...`

**Comment by tommysitu** [comment] 2017-05-12 19:14
Thanks @liclac I am going to try it, but how do I set `k6 run` to use a proxy server?  Is there any equivalent option to `--proxy` in `curl` ?

**Comment by liclac** [comment] 2017-05-12 22:11
Set HTTP_PROXY (and/or HTTP_PROXY) in the environment

**Comment by tommysitu** [comment] 2017-05-13 21:15
This is what I've tried, it didn't work:
```
Tommys-MBP:k6 tommysitu$ export HTTP_PROXY=junior-tennis-tommysitu.hoverfly.io:8500
Tommys-MBP:k6 tommysitu$ export HTTPS_PROXY=junior-tennis-tommysitu.hoverfly.io:8500
Tommys-MBP:k6 tommysitu$ k6 run --insecure-skip-tls-verify hfc.js

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/  Welcome to k6 v0.14.0!

  execution: local
     output: -
     script: /Users/tommysitu/playground/k6/hfc.js (js)

   duration: 0s, iterations: 1
        vus: 1, max: 1

    web ui: http://127.0.0.1:6565/

ERRO[0000] GoError: Get https://www.my-test.com/api/bookings/1: dial tcp 5.22.149.135:443: getsockopt: connection refused
	at native
	at /Users/tommysitu/playground/k6/hfc.js:8:77(13)

      done [==========================================================]      100ms / 100ms

    data_received.........: 0 B
    data_sent.............: 0 B
    errors................: 1
    http_req_blocked......: avg=175.2ms max=175.2ms med=175.2ms min=175.2ms p90=175.2ms p95=175.2ms
    http_req_connecting...: avg=50.6ms max=50.6ms med=50.6ms min=50.6ms p90=50.6ms p95=50.6ms
    http_req_duration.....: avg=0s max=0s med=0s min=0s p90=0s p95=0s
    http_req_receiving....: avg=0s max=0s med=0s min=0s p90=0s p95=0s
    http_req_sending......: avg=0s max=0s med=0s min=0s p90=0s p95=0s
    http_req_waiting......: avg=0s max=0s med=0s min=0s p90=0s p95=0s
    http_reqs.............: 1
    iterations............: 1
    vus...................: 1
    vus_max...............: 1
Tommys-MBP:k6 tommysitu$
```

The js file looks like this:
```
import http from "k6/http";

export default function() {

let params = {
		headers: { "Proxy-Authorization": "Bearer sometoken" }
	};
  let result =  http.get("https://www.my-test.com/api/bookings/1", params);
};
```

**Comment by liclac** [comment] 2017-05-15 14:00
Alright, that's a bug, please open another issue for it; this one is getting off topic.

**Comment by tommysitu** [comment] 2017-05-15 14:09
What @micsjo suggested makes sense, and there isn't real benefit of using custom ca cert for load testing, and there is `--insecure-skip-tls-verify` to disable certificate verification. 

Feel free to close this issue.

**Comment by liclac** [comment] 2017-05-15 15:16
👍

**Closed by liclac** 2017-05-15 15:16 UTC

**Comment by Huixxi** [comment] 2023-02-16 08:52
> It exists! `k6 run --insecure-skip-tls-verify ...`

But I just want to test the tls duration, why you don't support curl like --caacert? It's not that difficult right?
