### ISSUE TITLE
When call fail after check, check will not be count in the `checks` result

### ISSUE THREAD

**Issue by owenhuang2017** [loadimpact/k6#669] opened 2018-06-08 02:25 UTC
Test code with calling fail():
```// K6 built in modules
import { check, sleep, fail } from "k6";

// K6 testing options
export let options = {
    stages: [
        { duration: "5s", target: 5 },
        { duration: "30s" },
        { duration: "5s", target: 0 }
    ]
};

export default function() {
    sleep(0.1);

    var date = new Date();
    
    check(date, {
        "milliseconds < 500": (r) => r.getMilliseconds() < 500
    }) || fail("milliseconds >= 500");
};
```
Result:
```    ✗ milliseconds < 500
     ↳  50% — ✓ 872 / ✗ 858

    checks...............: 100.00% ✓ 872 ✗ 0  
    data_received........: 0 B     0 B/s
    data_sent............: 0 B     0 B/s
    iteration_duration...: avg=102.38ms min=100.07ms med=102.52ms max=105.27ms p(90)=104.63ms p(95)=104.9ms
    iterations...........: 1734    43.349749/s
    vus..................: 1       min=1 max=5
    vus_max..............: 5       min=5 max=5
```

Test code without calling fail():
```// K6 built in modules
import { check, sleep, fail } from "k6";

// K6 testing options
export let options = {
    stages: [
        { duration: "5s", target: 5 },
        { duration: "30s" },
        { duration: "5s", target: 0 }
    ]
};

export default function() {
    sleep(0.1);

    var date = new Date();
    
    check(date, {
        "milliseconds < 500": (r) => r.getMilliseconds() < 500
    });
};
```
Result:
```    ✗ milliseconds < 500
     ↳  50% — ✓ 874 / ✗ 860

    checks...............: 50.40% ✓ 874 ✗ 860
    data_received........: 0 B    0 B/s
    data_sent............: 0 B    0 B/s
    iteration_duration...: avg=102.17ms min=100.08ms med=101.87ms max=105.28ms p(90)=104.54ms p(95)=104.88ms
    iterations...........: 1738   43.449626/s
    vus..................: 1      min=1 max=5
    vus_max..............: 5      min=5 max=5
```

**Comment by luizbafilho** [comment] 2018-08-02 18:58
Hi @owenhuang2017,

Just tried to reproduce the problem but I wasn't able to, I guess the latest changes fixed that. Could you try the newest version of k6 and let me know if the problem persists?

**Comment by na--** [comment] 2018-10-05 06:38
Closing this since it was inadvertently fixed by the [real-time metrics refactoring](https://github.com/loadimpact/k6/pull/678) that was [part of the k6 v0.22.0 release](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.22.0.md#real-time-metrics-678).

**Closed by na--** 2018-10-05 06:38 UTC
Labels: bug
