### ISSUE TITLE
Test upload tar.gz failed

### ISSUE THREAD

**Issue by lynchmaniac** [loadimpact/k6#396] opened 2017-12-04 09:54 UTC
K6 is a great tool but i have an issue when i use it with Openstack/Swift API.
Swift is an object storage. The API that i test is to upload a tar.gz and tell swift to unpack the tar.
This test failed in : 
```
INFO[0000] Number Files Created: 0
Response Body: Invalid Tar File: not a gzip file
Response Status: 400 Bad Request
Errors:
``` 
This is the test code
```
import http from "k6/http";
let archive = open("./archive.tar.gz");
export let params =  { headers: { "X-Auth-Token": "XXXXX", "Content-Type":"application/tar+gzip" } };

export default function() {
  var res = http.put("http://localhost:8080/v1/AUTH_XXXX/k6archive?extract-archive=tar.gz", archive, params);
```
In the  k6/js/modules/k6/http/http.go file, we ca see this code
```
if rt.ExportTo(args[0], &data) == nil {
			bodyQuery := make(neturl.Values, len(data))
			for k, v := range data {
				bodyQuery.Set(k, v.String())
			}
			bodyReader = bytes.NewBufferString(bodyQuery.Encode())
			contentType = "application/x-www-form-urlencoded"
		} else {
			bodyReader = bytes.NewBufferString(args[0].String())
}
```
Is the test fail because we have a BufferString and a args[0].String() for a tar.gz file ? Or did i miss something to pass the test ?

**Comment by liclac** [comment] 2017-12-08 02:23
This needs #269

**Comment by liclac** [comment] 2017-12-10 17:13
I'm actually just going to close this as a duplicate of that issue.

**Closed by liclac** 2017-12-10 17:13 UTC
