### ISSUE TITLE
K6 not running in git bash

### ISSUE THREAD

**Issue by adamb1987** [loadimpact/k6#1359] opened 2020-03-13 12:58 UTC
Trying to execute a run in git bash give the following response

![image](https://user-images.githubusercontent.com/33325197/76622781-13984700-652a-11ea-9664-b87bf5793d3e.png)

Switched to `cmd` and same file executes as expected

## Environment
Windows 10 - git version 2.25.0.windows.1

## Expected Behavior
Should run in all terminal versions

**Comment by sniku** [comment] 2020-03-17 10:47
We weren't able to reproduce this problem with the same Windows and git-bash version you are using.
Is it possible that you have something else in your environment that causes this problem?

![image (9)](https://user-images.githubusercontent.com/442646/76849113-11ddc480-6845-11ea-8eb4-1eec59503dba.png)

**Comment by mostafa** [comment] 2020-03-17 10:52
Can it be due to the dash in the filename?

**Comment by MStoykov** [comment] 2020-11-06 09:07
closing this based on the fact that the original reported hasn't come back and it seems to work for us. 
@adamb1987  if the issues still persists, please comment here and I will reopen it.

**Closed by MStoykov** 2020-11-06 09:07 UTC
Labels: bug, help wanted
