### ISSUE TITLE
ramda.js not working

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#339] opened 2017-10-16 18:24 UTC
The below, reported by askierniewski@slack, happens when the script further down is run:

```
ERRO[0009] TypeError: Cannot read property 'find' of undefined========]      700ms / 0s
	at cdnjs.cloudflare.com/ajax/libs/ramda/0.25.0/ramda.min.js:1:3486(51)
	at e (cdnjs.cloudflare.com/ajax/libs/ramda/0.25.0/ramda.min.js:1:1069(76))
	at /Users/ragnarlonn/src/go/src/github.com/loadimpact/k6/askierniewski.js:29:24(12)
	at native
	at /Users/ragnarlonn/src/go/src/github.com/loadimpact/k6/askierniewski.js:27:17(32)
```

The script:

```
import * as R from "cdnjs.cloudflare.com/ajax/libs/ramda/0.25.0/ramda.min.js"
import {group, sleep, check} from "k6"
import http from "k6/http"

const parseBody = res => {
  let res2 = R.clone(res) // just to be sure that I'm not working on original object
  if (R.is(String(res.body) && !R.isEmpty(res.body) && R.isEmpty(res.error))) {
    try { // Remove try catch block to get "SyntaxError: EOF" on valid JSON
      res.body = JSON.parse(res.body)
    } catch (err) {
      // "SyntaxError: EOF" error is thrown as part of execution teardown
      console.error('JSON.parse ERROR!') // Adding try catch removes SyntaxError but it wont log this line ?!
    }
  }
  return res2
}

export default function() {

  const productId = 1
 
  let res = http.get("https://api.dev.peachworks.com/v1/products")

  const products = parseBody(res).results
  sleep(0.1)

  group("xxx", function() {

    const setup2 = R.find(R.propEq('id', productId), products)
    sleep(0.1)

    group("yyy", function() {

      const setup3 = R.find(R.propEq('id', productId), products)
      sleep(0.1)
    })

  })
}
```

**Comment by liclac** [comment] 2017-10-16 18:27
What precisely happens when you do this, and what do you expect will happen?

**Comment by ragnarlonn** [comment] 2017-10-16 18:45
Precisely that error message happens. I have no idea what should happen though :)   Looking briefly at the ramda.js docs, it seems R.clone() will make a deep copy of the obj, and then R.find() "returns the first element of the list which matches the predicate". Hmm, a list?

**Comment by ppcano** [comment] 2017-10-16 19:00
The problem importing the `ramda` library is due that the library is exporting the  `_esModule` flag. 

```
Object.defineProperty(exports, '__esModule', { value: true });
```

If this statement is commented or the `value` is set to `false`, the `ramda` import will work.

**Comment by ppcano** [comment] 2017-10-16 19:44
Closing it because the problem looks a bug in the `parseBody` function.
```
export default function() {

  const productId = 1

  let res = http.get("https://api.dev.peachworks.com/v1/products")

  const products = JSON.parse(res.body).results
  sleep(0.1)


  group("xxx", function() {

    const product = R.find(R.propEq('id', productId), products)
    check(product, {
      "product 1 found": () => product && product.id === productId
    });
    sleep(0.1)

    group("yyy", function() {

      const product2 = R.find(R.propEq('id', productId), products)
      check(product2, {
        "product 2 found": () => product2 && product2.id === productId
      });
      sleep(0.1)
    })

  })
}
```

Please, open a stackoverflow question for this type of questions. 

https://github.com/loadimpact/k6#need-help-or-want-to-contribute

**Closed by ppcano** 2017-10-16 19:44 UTC

**Comment by AdrianSkierniewski** [comment] 2017-10-16 19:50
@liclac @ragnarlonn @ppcano Please don't suggest that clone call it's irrelevant (probably whole ramda) to this issue. Here is a more simplistic version with a different error.
```
ERRO[0021] SyntaxError: EOF==========================================] -- / --
	at parse (native)
	at /scripts/k6/tests/panera/example.js:26:29(19)
```
This error is probably related to that ramda issue later and it looks like the root cause of it is related to usage of `stages`. Errors disappear after removing stages.
```JavaScript
import * as R from "cdnjs.cloudflare.com/ajax/libs/ramda/0.25.0/ramda.min.js"
import {group, sleep, check} from "k6"
import http from "k6/http"

export let options = {
  stages: [
    {duration: "20s", target: 5},
    {duration: "10s"},
    {duration: "50s", target: 20},
    {duration: "10s"},
    {duration: "50s", target: 40},
    {duration: "10s"},
    {duration: "50s", target: 60},
    {duration: "100s"},
    {duration: "30s", target: 40},
    {duration: "20s"},
  ]
}

export default function() {

  const productId = 1
  // Get all locations to reuse them in tests
  let res = http.get("https://api.dev.peachworks.com/v1/products")

  const products = JSON.parse(res.body).results
  sleep(0.1)

  group("xxx", function() {

    const setup2 = R.find(R.propEq('id', productId), products)
    sleep(0.1)

    group("yyy", function() {

      const setup3 = R.find(R.propEq('id', productId), products)
      sleep(0.1)
    })

  })
}
```
Should I create a separate issue for this?

**Comment by ppcano** [comment] 2017-10-16 20:24
I reproduced this case in the following [gist](https://gist.github.com/ppcano/e0ec364834e4254974e3991bc178cd46).

The problem with the above script is that wrong data will be passed to the `ramda` library when the response fails.

It looks to exist a bug that reports wrongly `checks` when using `stages`. This possible bug has confused the issue investigation. I will try to reproduce it again and will create a new issue.

**Comment by gewfy** [comment] 2017-11-02 14:27
I've reproduced this without using `stages` or `rambda`. 

This tiny test:
```javascript
import { check } from 'k6';
import http from 'k6/http';

export default function () {
  const res = http.get('https://api.dev.peachworks.com/v1/products');

  check(res, {
    'status is 200': res => res.status === 200
  });

  const products = JSON.parse(res.body).results;

  check(products, {
    'products is not empty': products => products.length > 0
  });
}
```

Produces the `SyntaxError` problem but no check errors:
![image](https://user-images.githubusercontent.com/474066/32331072-3b373d88-bfe2-11e7-9cc8-d6d6c632ea29.png)
