### ISSUE TITLE
Ability to read environment variables from test files

### ISSUE THREAD

**Issue by yolinas** [loadimpact/k6#95] opened 2017-01-31 15:55 UTC
We are currently unable to access shell environment variables from within the test files. 

In our case, we would like to be able to get the url of the system under test from previously set environment variable since we would like to be able to spin up a new performance environment every time we run the tests.

**Comment by uppfinnarn** [comment] 2017-02-01 16:05
Here, then, is the big question I'm half afraid of asking, because this is gonna turn into bikeshedding:

Do we want to copy `process.env` from node, or do we want to go with `__ENV`? We can't really implement anything else out of Node's `process` object…

**Comment by ragnarlonn** [comment] 2017-02-02 11:11
If we can't implement anything else from `process` my opinion is we should not use that name. It is likely to cause confusion and set the wrong expectations. @yolinas herself assumed we were running node when she first tried using k6. If we use node-specific keywords in our API people are even more likely to assume we are running node in the background and then probably run into all sorts of trouble trying to use various node functionality. IMO we should only use nomenclature from other projects when we can implement most or all of the functionality users of those projects are used to having.

**Comment by uppfinnarn** [comment] 2017-02-02 11:59
Implemented in 22d0e76c0632cbef9d31646b3f216a21813d4d26!

**Comment by liclac** [comment] 2017-05-16 17:22
Regression: broken in the js2 runner, fixing…

**Comment by liclac** [comment] 2017-05-18 16:40
Fixed in 6c3a0526f626e6964993aebb80a51da44e58c811

**Closed by liclac** 2017-05-18 16:40 UTC
Labels: enhancement
