### ISSUE TITLE
panic: open babel-standalone-bower/babel.min.js: file does not exist

### ISSUE THREAD

**Issue by 479123512** [loadimpact/k6#689] opened 2018-07-05 06:13 UTC
MAC environment, follow the instructions after installation, run the k6 command, this error appears, please answer this question.

![image](https://user-images.githubusercontent.com/28186048/42305440-8a0ac54c-805d-11e8-9a9c-d7f2dcff5493.png)

![image](https://user-images.githubusercontent.com/28186048/42305419-74029da6-805d-11e8-84df-843243804ee3.png)

**Comment by na--** [comment] 2018-07-06 11:20
@479123512, thanks for reporting this, can you share a bit more information about the issue, since we couldn't reproduce it on our machines? Initially I thought the problem was caused by [this PR](https://github.com/loadimpact/k6/pull/658) and did [this](https://github.com/loadimpact/homebrew-k6/pull/3) as a fix, but @robingustafsson noticed that we actually merged that pull request after releasing 0.21.1, so it couldn't be the reason for the issue. And a couple of people installed and ran k6 from homebrew without any issues as it was..

So we need more information to diagnose this... What are your OS, homebrew and git versions? And what's the output of the `which k6` command? I'm concerned that it might not be the binary installed by homebrew but instead the path to a binary that was installed via `go get github.com/loadimpact/k6` or something like that.

**Comment by robingustafsson** [comment] 2018-07-06 16:20
Oops, mistake auto-close caused by merge in k6-homebrew repo ([this PR](https://github.com/loadimpact/homebrew-k6/pull/3)).

**Comment by na--** [comment] 2018-07-06 20:01
As we just released 0.22, @479123512 can you see if the problem persists with the new version as well. This time there's no go.rice involved in the build steps, so it should hopefully be gone.

**Comment by na--** [comment] 2018-10-04 13:32
Closing this since the issue should have been fixed a long time time. Feel free to reopen if that's not the case though.

**Closed by na--** 2018-10-04 13:32 UTC
Labels: bug
