### ISSUE TITLE
Set No of TCP Conns

### ISSUE THREAD

**Issue by aidylewis** [loadimpact/k6#245] opened 2017-06-13 06:34 UTC
Any way of setting the number of TCP connections without interfering with the ulimit?

**Comment by liclac** [comment] 2017-06-13 13:37
Could you elaborate?

By default, connections are reused between VU iterations because otherwise we chew through most OSes' default ulimit far too quickly to be of any use; pass `--no-connection-reuse` to disable this behaviour. Are you asking for a way to limit the number of TCP connections used when they're not reused?

**Comment by robingustafsson** [comment] 2017-06-13 13:38
Duplicate of https://github.com/loadimpact/k6/issues/215?

**Comment by liclac** [comment] 2017-08-07 19:30
Poke.

**Comment by aidylewis** [comment] 2017-08-07 21:03
Can be done through iptables.

**Comment by liclac** [comment] 2017-08-07 21:26
Alright, closing this then.

**Closed by liclac** 2017-08-07 21:26 UTC

**Comment by aidylewis** [comment] 2017-09-08 15:56
Can be done with the **noConnectionReuse** flag. I tested with one request == one TCP connection and socket statistics.
