### ISSUE TITLE
Checks failing during setup aren't reported individually

### ISSUE THREAD

**Issue by neerolyte** [loadimpact/k6#993] opened 2019-04-09 06:50 UTC
Example k6 script:

```javascript
$ cat foo.js 
import { check } from "k6";
export function setup() {
        check(false, { "setup": (t) => t })
};
export default function() {
        check(false, { "test": (t) => t })
};
```

Example run:

```
$ docker run -it --rm -v "$PWD:/src" -w /src loadimpact/k6 run foo.js
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: foo.js

    duration: -,  iterations: 1
         vus: 1, max: 1

    done [==========================================================] 1 / 1

    ✗ test
     ↳  0% — ✓ 0 / ✗ 1

    checks...............: 0.00% ✓ 0   ✗ 2  
    data_received........: 0 B   0 B/s
    data_sent............: 0 B   0 B/s
    iteration_duration...: avg=38.31µs min=27.43µs med=38.31µs max=49.2µs p(90)=47.02µs p(95)=48.11µs
    iterations...........: 1     0/s
    vus..................: 1     min=1 max=1
    vus_max..............: 1     min=1 max=1
```

Note that:

 * only the “test” check shows as failed explicitly
 * two checks failed overall: `checks...............: 0.00% ✓ 0 ✗ 2` (but we’re left to guess at what the other failure was)

**Comment by na--** [comment] 2019-04-09 17:47
Closing this since it's a duplicate of https://github.com/loadimpact/k6/issues/949

**Closed by na--** 2019-04-09 17:47 UTC
