### ISSUE TITLE
Streaming to LoadImpact cloud throws error at the end and never finishes

### ISSUE THREAD

**Issue by carl-thomas** [loadimpact/k6#507] opened 2018-02-15 08:21 UTC
When I run

`K6_CLOUD_TOKEN=<TOKEN> k6 run --vus 10 -d 30s - cloud <FILE>`

It runs for the full 30s and streams all the results to LoadImpact cloud. However, right at the end I get the following warning 

`WARN[0034] Failed to send test finished to cloud          error="An internal error occurred"`

This means that all my test results in LoadImpact cloud are never finished but state that they have Timed Out

**Comment by robingustafsson** [comment] 2018-02-15 09:07
Thanks @carl-thomas, we're looking into the cause of this. Will post here when it's fixed.

**Comment by robingustafsson** [comment] 2018-02-15 10:21
@carl-thomas This issue has now been fixed in the cloud service. Thanks again for reporting!

**Closed by robingustafsson** 2018-02-15 10:21 UTC
