### ISSUE TITLE
HTTP socket options

### ISSUE THREAD

**Issue by micsjo** [loadimpact/k6#215] opened 2017-05-11 13:07 UTC
Based on experience with current load generator scripting we know users have a need to customize the HTTP client behavior, this card details what options we need.

HTTP Options (set globally)
 TCP max connections per host
 TCP max connections per VU
 User agent string

HTTP options (local, request functions)
 ...

**Comment by liclac** [comment] 2017-12-04 16:26
The user agent string is already there, the caps per host/VU only make sense in the context of http.batch (#296), gonna close this as a duplicate of that one.

**Closed by liclac** 2017-12-04 16:26 UTC
